// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpnnrpkpevobtqqrfrzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbm5ycGtwZXZvYnRxcXJmcnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTQwMDQsImV4cCI6MjA3MjMzMDAwNH0.mi_luKY_QMeVimJ5kXq095_VabvBNNC1PZ5Btnzw5rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});